apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-joker-staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: the-joker
spec:
  project: default
  source:
    path: the-joker/overlays/staging
    repoURL: https://github.com/salesdemocf/codefresh-pov-configs.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false