apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-name-application-environment
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: application-name
spec:
  project: default
  source:
    path: application-name/application-environment
    repoURL: config-repository
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: destination-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false